encoding: utf-8

# SEO相关信息
title: zhoudajun's Blog
description: 对结果负责，用作品说话
keywords: zhoudajun,Blog,python,AI,read
author: zhoudajun
#footerText: 'Copyright © 2016 皖ICP备16016174号'

# 留言配置, 不需要的话值设置为空，同时删除 # 菜单 配置项中的留言页面
# 官网 https://www.bmob.cn
# 文档 https://bmob.github.io/hydrogen-js-sdk
# 建议自己申请一个，表结构如下
# 表名 Comment ,字段如下 
# url      String
# time     Date
# nickName String
# email    String
# content  String
# website  String
# bmobApplicationId: 34f0386ac5bd50fd77fe82190af00faf
# bmobRestApiKey: 6f1419c800083315432f2df7dcb503d4

# 域名配置
# baseUrl配置,如果网站部署在根目录下的目录中，请设置为 /目录名
domainUrl: 'https://zhoudajun.club/'
baseUrl: ''

# 菜单
menu:
  - title: Home
    url: /
  - title: Categories
    url: /pages/categories.html
  - title: Search
    url: /pages/search.html
  # - title: Links
   # url: /pages/links.html
  # - title: Chat
   # url: /pages/chat.html
  - title: About
    url: /pages/about.html

# 腾讯移动分析设置
# 官网 https://mta.qq.com
# 如果需要请申请自己的，sid，cid 在统计代码里找
# 不需要请设置为false，mtaSid，mtaCid置空
mta: false
mtaSid: 
mtaCid: 

#gitment

gitment:
  enable: true
  mint: true        # RECOMMEND, A mint on Gitment, to support count, language and proxy_gateway
  count: true       # Show comments count in post meta area
  lazy: false       # Comments lazy loading with a button
  cleanly: false    # Hide 'Powered by ...' on footer, and more
  language:         # Force language, or auto switch by theme
  github_user: zhoudajun # 此处 - Your Github ID
  github_repo: zhoudajun.github.io # 此处注意 - The repo you use to store Gitment comments
  client_id: 1c1e5f846ea94bd66d7e   # 此处 - Github client id for the Gitment
  client_secret: 4158fd2b0b53c60389068b49ef801f55e170473f # 此处 - Github access secret token for the Gitment
  proxy_gateway: # Address of api proxy, See: https://github.com/aimingoo/intersect
  redirect_protocol: # Protocol of redirect_uri with force_redirect_protocol when mint enabled

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'build-tool']
